#' Get official data about Covid-19 cases in Mexico
#'
#' Get official data about Covid-19 cases in Mexico. Main data source is Mexico's
#' Federal Government Ministry of Health (Secretaría de Salud). It should be noted, however,
#' that the open data format of the daily report is generated by third parties, since the original
#' report is a PDF document.
#'
#' @return A `tibble` with 8 columns:
#' Case Number, State, Sex, Age, Symptoms Onset Date, COVID-19 Test Result, Country Visited,
#' Date of Arrival to Mexico
#'
#' @param type Get `confirmed` or `suspect` cases?. `character` vector of length 1.
#' @param date Date (version) of the published results. `character` vector of length 1 or `date` object.
#' @param source Data source. Mexico's Ministry of Health publishes a daily report containing data about
#' positive and suspected cases of Covid-19 cases in the country.
#' However, the data is published as a PDF document, difficulting further analysis.
#' This package relies on third party sources to get an "open data" version of the report.
#' `character` vector of length 1. Possible data sources are: `Serendipia`.
#'
#' @import lubridate
#' @import stringr
#' @import httr
#' @export

getData <- function(type = "confirmed", date = "today", source = "Serendipia") {
  # First some type and value check
  if (!is.character(type) | length(type) > 1 ) {
    stop("'type' par must be a character vector of length 1!")
  }
  if (!is.character(source) | length(source) > 1 ) {
    stop("'source' par must be a character vector of length 1!")
  }
  if (!is.Date(date) & !is.character(date) | length(date) > 1) {
    stop("'date' par must be a date object or a character vector of length 1!")
  }

  # Try to parse date as date
  if (!is.Date(date)) {
    # If str = today use today's date, else use dmy
    if (date == "today") parsedDate <- today() else parsedDate <- dmy(date, quiet = T)
  }

  # User can choose between data sources
  # As of v. 0.1.0, only Serendipia is available
  if (tolower(source) == "serendipia") {
    # get URL of the documents
    hrefs <- covidMex::parseSerendipia()

    # Filter urls (confirmed vs suspected cases)
    # First create a regex patter that depends on the type of cases
    if (type == "confirmed") {
      pattern <- "(?=positivos).*_(\\d*.\\d*.\\d*)"
    }  else if (type == "suspect") {
      pattern <- "(?=sospechosos).*_(\\d*.\\d*.\\d*)"
    } else {
      stop("Unknown data type! Available data types: 'confirmed' or 'suspect'")
    }

    # Filter
    hrefs <- hrefs[grepl(pattern = pattern, x = hrefs, perl = T)]

    # Get dates of the documents
    # The second column of the matrix corresponds to the date in the document name
    dates <- str_match(hrefs, pattern = pattern)[,2]

    # Get parsed version of the dates
    parsedDates <- parse_date_time(x = dates, orders = "%Y.%m.%d")

    # Build a tibble with the data
    cat <- tibble(hrefs, dates, parsedDates)

    # Try to get data from today's date
    continue <- TRUE
    count <- 1
    while (continue) {
      # Subset comparing parsedDate
      catSubset <- cat[cat$parsedDates == parsedDate,]
      # Count number of rows of subset result
      # No rows means that there's not yet data for today
      if (nrow(catSubset) == 0) {
        if (count > 5) {
          stop(paste("The specified date (", parsedDate ,") is not available (stopped because too many attempts)",
                     sep = ""))
        }
        count <- count + 1
        warning(paste("The specified date (", parsedDate ,") is not available... trying yesterday's date instead",
                      sep = ""))
        parsedDate <- parsedDate - days(1)
      } else {
        continue <- FALSE
      }
    }

    # Get URL from subset result
    targetURL <- catSubset$hrefs[1]

    # Define temp file name
    fileExt <- str_match(targetURL, ".*\\.(\\w+)")[,2]
    targetFile <- tempfile("covid19Mex_", fileext = fileExt)

    # Make request and save response file in temp directory
    GET(url = targetURL, write_disk(targetFile, overwrite = T),
        add_headers(`User-Agent` = "R Package (covidMex)",
                    `X-Package-Version` = as.character(packageVersion("covidMex")),
                    `X-R-Version` = R.version.string))

    # Read file
    data <- read_csv(targetFile)

  } else {
    stop("Unknown data source! Available data sources: 'Serendipia'")
  }

  return(data)
}
