#' Get official data about Covid-19 cases in Mexico
#'
#' Get official data about Covid-19 cases in Mexico. Main data source is Mexico's
#' Federal Government Ministry of Health (Secretaría de Salud). It should be noted, however,
#' that the open data format of the daily report is generated by third parties, since the original
#' report is a PDF document.
#'
#' @return A `tibble` with 8 columns:
#' Case Number, State, Sex, Age, Symptoms Onset Date, COVID-19 Test Result, Country Visited,
#' Date of Arrival to Mexico
#'
#' @param type Get `confirmed` or `suspect` cases?. `character` vector of length 1.
#' @param date Date (version) of the published results. `character` vector of length 1 or `date` object.
#' @param source Data source. Mexico's Ministry of Health publishes a daily report containing data about
#' positive and suspected cases of Covid-19 cases in the country.
#' However, the data is published as a PDF document, difficulting further analysis.
#' This package relies on third party sources to get an "open data" version of the report.
#' `character` vector of length 1. Possible data sources are: `Serendipia`.
#'
#' @export

getData <- function(type = "confirmed", date = "today", source = "Serendipia") {
  # First some type and value check
  if (!is.character(type) | length(type) > 1 ) {
    stop("'type' par must be a character vector of length 1!")
  }
  if (!is.character(source) | length(source) > 1 ) {
    stop("'source' par must be a character vector of length 1!")
  }
  if (!is.Date(date) & !is.character(date) | length(date) > 1) {
    stop("'date' par must be a date object or a character vector of length 1!")
  }

  # Try to parse date as date
  if (!is.Date(date)) {
    # If str = today use today's date, else use dmy
    if (date == "today") parsedDatePar <- today() else parsedDatePar <- dmy(date, quiet = T)
  } else {
    parsedDatePar <- date
  }

  # User can choose between data sources
  # As of v. 0.2.0, Serendipia and Guzmanart are available
  # User asked for Serendipia as data source
  if (tolower(source) == "serendipia") {
    data <- covidMex::GetFromSerendipia(type = type, date = parsedDatePar)
  # User asked for Guzmaart GitHub page as data source
  } else if (tolower(source) == "guzmart") {
    # Guzmart has no suspect cases data :(
    if (type == "suspect") {
      stop("Sorry! The suspect cases table is only available in Serendipia's data page. Please use source='Serendipia'")
    }
    data <- covidMex::GetFromGuzmart(date = parsedDatePar)
  } else {
    stop("Unknown data source! Available data sources: 'Serendipia'")
  }

  return(data)
}
