#' Get official data about Covid-19 cases in Mexico
#'
#' Get official data about Covid-19 cases in Mexico. Main data source is Mexico's
#' Federal Government Ministry of Health (Secretaría de Salud). It should be noted, however,
#' that the open data format of the daily report is generated by third parties, since the original
#' report is a PDF document. Wrapper for \code{\link{GetFromSerendipia}}, and \code{\link{GetFromGuzmart}}
#'
#' @return A `tibble` with 8/9 columns:
#' Case Number, State, Sex, Age, Symptoms Onset Date, COVID-19 Test Result, Country Visited,
#' Date of Arrival to Mexico, and date when the case officialy registered (only available if `source = "Guzmart"`).
#'
#' @param type Get `confirmed` or `suspect` cases?. `character` vector of length 1.
#' @param date Date (version) of the published results. `character` vector of length 1 or `date` object.
#' @param source Data source. Mexico's Ministry of Health publishes a daily report containing data about
#' positive and suspected cases of Covid-19 cases in the country.
#' However, the data is published as a PDF document, difficulting further analysis.
#' This package relies on third party sources to get an "open data" version of the report.
#' `character` vector of length 1. As of version 0.2.0, possible data sources are:
#' `Serendipia` (confirmed, suspect), and `Guzmart` (confimed).
#' @param neat Should data be cleaned (dates, state name, column names)? `logical` vector of length 1.
#'
#' @export

getData <- function(type = "confirmed", date = "today", source = "Guzmart", neat = TRUE) {
  # First some type and value check
  if (!is.character(type) | length(type) > 1 ) {
    stop("'type' par must be a character vector of length 1!")
  }
  if (!is.character(source) | length(source) > 1 ) {
    stop("'source' par must be a character vector of length 1!")
  }
  if (!is.Date(date) & !is.character(date) | length(date) > 1) {
    stop("'date' par must be a date object or a character vector of length 1!")
  }

  # Try to parse date as date
  if (!is.Date(date)) {
    # If str = today use today's date, else use dmy
    if (date == "today") parsedDatePar <- today() else parsedDatePar <- dmy(date, quiet = T)
  } else {
    parsedDatePar <- date
  }

  # User can choose between data sources
  # As of v. 0.2.0, Serendipia and Guzmart are available
  # User asked for Serendipia as data source
  if (tolower(source) == "serendipia") {
    data <- covidMex::GetFromSerendipia(type = type, date = parsedDatePar, neat = neat)
  # User asked for Guzmart GitHub page as data source
  } else if (tolower(source) == "guzmart") {
    # Guzmart has no suspect cases data :(
    if (type == "suspect") {
      stop("Sorry! The suspect cases table is only available in Serendipia's data page. Please use source='Serendipia'")
    }
    data <- covidMex::GetFromGuzmart(date = parsedDatePar, neat = neat)
  } else {
    stop("Unknown data source! Available data sources: 'Serendipia'")
  }

  return(data)
}

#' Get official record of confirmed Covid-19 cases in Mexico
#'
#' Get official record of confirmed Covid-19 cases in Mexico. This is a wrapper for \code{\link{getData}} that downloads the most recent
#' official report (Mexico's Ministry of Health) of Covid-19 cases in the country.
#'
#' @return A `tibble` with 9 columns:
#' Case Number, State, Sex, Age, Symptoms Onset Date, COVID-19 Test Result, Country Visited,
#' Date of Arrival to Mexico, and Date when the case officialy registered.
#'
#' @export
covidConfirmedMx <- function() {
  data <- getData(type = "confirmed", date = "today", source = "Guzmart")
  return(data)
}

#' Get official record of suspected Covid-19 cases in Mexico
#'
#' Get official record of suspected Covid-19 cases in Mexico. This is a wrapper for \code{\link{getData}} that downloads the most recent
#' official report (Mexico's Ministry of Health) of suspected Covid-19 cases in the country.
#'
#' @return A `tibble` with 8 columns:
#' Case Number, State, Sex, Age, Symptoms Onset Date, COVID-19 Test Result, Country Visited, and
#' Date of Arrival to Mexico.
#'
#' @export
covidSuspectsMx <- function() {
  data <- getData(type = "suspect", date = "today", source = "Serendipia")
  return(data)
}
